//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okun.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int RecordNumber { get; set; }
        public int ElectronicsCode { get; set; }
        public string FIO { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public int QuantityProduct { get; set; }
    
        public virtual Information Information { get; set; }
    }
}
